# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f052d4d4c71501ef067a4c0fe79360f1"
name = "fc-dev-php"
handle = "fc-dev-php"
application_url = "https://bulgarian-bottle-heads-sprint.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-development-fc-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_orders,read_products,read_shipping,unauthenticated_read_checkouts,unauthenticated_write_checkouts,write_checkouts,write_orders,write_products,write_shipping"

[auth]
redirect_urls = [
  "https://bulgarian-bottle-heads-sprint.trycloudflare.com/auth/callback",
  "https://bulgarian-bottle-heads-sprint.trycloudflare.com/auth/shopify/callback",
  "https://bulgarian-bottle-heads-sprint.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
